# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: cloud.ga.gov.au
subtitle: Patterns and best-practices

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: '/cloud'

# Author/Organization info to be displayed in the templates
author:
  name: GA Autobots
  url: mailto:autobots@ga.gov.au

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: ./
  internal: true
- text: Getting Started
  subcategories:
  - text: Things to Consider
    url: things_to_consider_sub.html
    internal: true
  - text: Best Practices
    url: best_practices_sub.html
    internal: true
  - text: Setting Up AWS Account
    url: setting_up_sub.html
    internal: true
  - text: Sunset Strategy
    url: sunset_strategy_sub.html
    internal: true
- text: Security  
  url: security_index.html
  internal: true
- text: Monitoring
  url: monitoring_index.html
  internal: true
- text: Cost Management
  url: cost_management_index.html
  internal: true  
- text: Data
  url: data_index.html
  internal: true
- text: Testing
  url: testing_index.html
  internal: true
- text: Patterns & Examples
  url: patterns_index.html
  internal: true
- text: Tools
  url: tools
  internal: true


# Style Variables
brand_color: "#2cb34a"
